/**
 * Do not edit directly, this file was auto-generated.
 */

export const ColorPrimary50 = "#f0f8fa";
export const ColorPrimary100 = "#e0f1f4";
export const ColorPrimary200 = "#c1e3e9";
export const ColorPrimary300 = "#a3d5df";
export const ColorPrimary400 = "#84c7d4";
export const ColorPrimary500 = "#208497"; // Primary brand color from lc-design
export const ColorPrimary600 = "#1a6a79";
export const ColorPrimary700 = "#144f5b";
export const ColorPrimary800 = "#0d353d";
export const ColorPrimary900 = "#071a1f";
export const ColorSecondary50 = "#f5f8f9";
export const ColorSecondary100 = "#ebf1f3";
export const ColorSecondary200 = "#d7e3e7";
export const ColorSecondary300 = "#c3d5db";
export const ColorSecondary400 = "#afc7cf";
export const ColorSecondary500 = "#7097af"; // Secondary brand color from lc-design
export const ColorSecondary600 = "#5a798c";
export const ColorSecondary700 = "#435b69";
export const ColorSecondary800 = "#2d3c46";
export const ColorSecondary900 = "#161e23";
export const ColorNeutral50 = "#f9fafb";
export const ColorNeutral100 = "#f3f4f6";
export const ColorNeutral200 = "#e5e7eb";
export const ColorNeutral300 = "#d1d5db";
export const ColorNeutral400 = "#9ca3af";
export const ColorNeutral500 = "#6b7280";
export const ColorNeutral600 = "#4b5563";
export const ColorNeutral700 = "#374151";
export const ColorNeutral800 = "#1f2937";
export const ColorNeutral900 = "#111827";
export const ColorSuccessDefault = "#8ea475";
export const ColorSuccessLight = "#cdd6c2";
export const ColorSuccessDark = "#5f7150";
export const ColorErrorDefault = "#9d0e0e";
export const ColorErrorLight = "#f7a1a1";
export const ColorErrorDark = "#6b0909";
export const ColorWarningDefault = "#e1a040";
export const ColorWarningLight = "#f1d3a7";
export const ColorWarningDark = "#9b6b2b";
export const ColorInfoDefault = "#3b6588";
export const ColorInfoLight = "#b8cee0";
export const ColorInfoDark = "#27445c";
export const ColorAccentOrange = "#df792e";
export const ColorAccentPurple = "#866aa0";
export const ColorAccentRed = "#9e3846";
export const ColorAccentRust = "#c6592e";
export const ColorAccentViolet = "#4e3f84";
export const ColorSurfaceDarkBase = "#14222e"; // DS2.0 dark card surface
export const ColorSurfaceDarkRaised = "#1a2c3a"; // DS2.0 raised dark surface
export const ColorSurfaceDarkSunken = "#0c1722"; // DS2.0 sunken dark surface
export const ColorBackgroundDark = "#111827"; // DS2.0 dark app background (== neutral-900)
export const ColorTextDarkPrimary = "#eef4f6"; // DS2.0 dark primary text
export const ColorTextDarkSecondary = "#aebfc7"; // DS2.0 dark secondary text
export const ColorTextDarkTertiary = "#71858f"; // DS2.0 dark muted text
export const Spacing0 = "0";
export const Spacing1 = "0.25rem"; // 4px - Base grid unit
export const Spacing2 = "0.5rem"; // 8px
export const Spacing3 = "0.75rem"; // 12px
export const Spacing4 = "1rem"; // 16px
export const Spacing5 = "1.25rem"; // 20px
export const Spacing6 = "1.5rem"; // 24px
export const Spacing7 = "1.75rem"; // 28px
export const Spacing8 = "2rem"; // 32px
export const Spacing9 = "2.25rem"; // 36px
export const Spacing10 = "2.5rem"; // 40px
export const Spacing11 = "2.75rem"; // 44px - Minimum touch target
export const Spacing12 = "3rem"; // 48px
export const Spacing14 = "3.5rem"; // 56px
export const Spacing16 = "4rem"; // 64px
export const Spacing05 = "0.125rem"; // 2px
export const Spacing15 = "0.375rem"; // 6px
export const Spacing25 = "0.625rem"; // 10px
export const Spacing35 = "0.875rem"; // 14px
export const TypographyFontFamilyBase =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif";
export const TypographyFontFamilyMono =
  "'SF Mono', 'Monaco', 'Inconsolata', 'Fira Mono', 'Droid Sans Mono', 'Source Code Pro', monospace";
export const TypographyFontSizeXs = "0.75rem"; // 12px
export const TypographyFontSizeSm = "0.875rem"; // 14px
export const TypographyFontSizeBase = "1rem"; // 16px
export const TypographyFontSizeLg = "1.125rem"; // 18px
export const TypographyFontSizeXl = "1.25rem"; // 20px
export const TypographyFontSize2xl = "1.5rem"; // 24px
export const TypographyFontSize3xl = "1.875rem"; // 30px
export const TypographyFontSize4xl = "2.25rem"; // 36px
export const TypographyFontSize5xl = "3rem"; // 48px
export const TypographyFontSize6xl = "3.75rem"; // 60px
export const TypographyFontWeightNormal = "400";
export const TypographyFontWeightMedium = "500";
export const TypographyFontWeightSemibold = "600";
export const TypographyFontWeightBold = "700";
export const TypographyLineHeightTight = "1.25";
export const TypographyLineHeightNormal = "1.5";
export const TypographyLineHeightRelaxed = "1.75";
export const Elevation1 = "0 4px 24px rgba(0, 0, 0, 0.35)"; // DS2.0 subtle layered elevation for cards
export const Elevation2 = "0 8px 32px rgba(0, 0, 0, 0.42)"; // DS2.0 medium elevation for dropdowns/popovers
export const Elevation3 = "0 14px 44px rgba(0, 0, 0, 0.48)"; // DS2.0 high elevation for drawers
export const Elevation4 = "0 18px 60px rgba(0, 0, 0, 0.55)"; // DS2.0 highest elevation for modals/overlays
export const BorderRadiusNone = "0";
export const BorderRadiusSm = "0.625rem"; // 10px - DS2.0 small
export const BorderRadiusMd = "0.75rem"; // 12px - DS2.0 default
export const BorderRadiusLg = "1.125rem"; // 18px - DS2.0 card radius
export const BorderRadiusXl = "1.5rem"; // 24px
export const BorderRadius2xl = "2rem"; // 32px
export const BorderRadiusFull = "9999px"; // Fully rounded
export const AnimationDurationFast = "150ms"; // Standard animation duration
export const AnimationEasingEaseIn = "ease-in";
export const AnimationEasingEaseOut = "ease-out";
export const AnimationEasingEaseInOut = "ease-in-out";
export const SizeInteractiveXsHeight = "1.5rem"; // 24px
export const SizeInteractiveXsPadding = "0.25rem 0.5rem";
export const SizeInteractiveXsFontSize = "0.75rem";
export const SizeInteractiveSmHeight = "2rem"; // 32px
export const SizeInteractiveSmPadding = "0.375rem 0.75rem";
export const SizeInteractiveSmFontSize = "0.875rem";
export const SizeInteractiveMdHeight = "2.5rem"; // 40px - Default
export const SizeInteractiveMdPadding = "0.5rem 1rem";
export const SizeInteractiveMdFontSize = "1rem";
export const SizeInteractiveLgHeight = "2.75rem"; // 44px - Minimum touch target
export const SizeInteractiveLgPadding = "0.625rem 1.25rem";
export const SizeInteractiveLgFontSize = "1.125rem";
export const SizeMinTouchWidth = "2.75rem"; // 44px minimum
export const SizeMinTouchHeight = "2.75rem"; // 44px minimum
